package uk.gov.gds.ier.validation.constants

import scala.collection.immutable.HashMap

object NationalityConstants {

  type Franchise = String
  object Franchise {
    def apply(str:String) = {
      require(
        str == fullValue ||
        str == europeanValue ||
        str == commonwealthValue ||
        str == britishTerritoriesValue ||
        str == crownDependenciesValue
      )
      str
    }
    private final val fullValue = "Full"
    private final val europeanValue = "EU"
    private final val commonwealthValue = "Commonwealth"
    private final val britishTerritoriesValue = "British Territories"
    private final val crownDependenciesValue = "British Crown Dependencies"

    final val full = Franchise(fullValue)
    final val european = Franchise(europeanValue)
    final val commonwealth = Franchise(commonwealthValue)
    final val britishTerritories = Franchise(britishTerritoriesValue)
    final val crownDependencies = Franchise(crownDependenciesValue)
  }

  case class ISOCountry(isoCode:String, franchise: Franchise*)
  
  lazy val countryNameToCodes = HashMap(
    "Afghanistan" -> ISOCountry("AF"),
    "Albania" -> ISOCountry("AL"),
    "Algeria" -> ISOCountry("DZ"),
    "American Samoa" -> ISOCountry("AS"),
    "Andorra" -> ISOCountry("AD"),
    "Angola" -> ISOCountry("AO"),
    "Anguilla" -> ISOCountry("AI", Franchise.britishTerritories),
    "Antigua and Barbuda" -> ISOCountry("AG", Franchise.commonwealth),
    "Argentina" -> ISOCountry("AR"),
    "Armenia" -> ISOCountry("AM"),
    "Aruba" -> ISOCountry("AW"),
    "Australia" -> ISOCountry("AU", Franchise.commonwealth),
    "Austria" -> ISOCountry("AT", Franchise.european),
    "Azerbaijan" -> ISOCountry("AZ"),
    "Bahamas" -> ISOCountry("BS", Franchise.commonwealth),
    "Bahrain" -> ISOCountry("BH"),
    "Bangladesh" -> ISOCountry("BD", Franchise.commonwealth),
    "Barbados" -> ISOCountry("BB", Franchise.commonwealth),
    "Belarus" -> ISOCountry("BY"),
    "Belgium" -> ISOCountry("BE", Franchise.european),
    "Belize" -> ISOCountry("BZ", Franchise.commonwealth),
    "Benin" -> ISOCountry("BJ"),
    "Bermuda" -> ISOCountry("BM", Franchise.britishTerritories),
    "Bhutan" -> ISOCountry("BT"),
    "Bolivia" -> ISOCountry("BO"),
    "Bonaire/St Eustatius/Saba" -> ISOCountry("BQ"),
    "Bosnia and Herzegovina" -> ISOCountry("BA"),
    "Botswana" -> ISOCountry("BW", Franchise.commonwealth),
    "Brazil" -> ISOCountry("BR"),
    "British Indian Ocean Territory" -> ISOCountry("IO", Franchise.britishTerritories),
    "British Virgin Islands" -> ISOCountry("VG", Franchise.britishTerritories),
    "Brunei" -> ISOCountry("BN", Franchise.commonwealth),
    "Bulgaria" -> ISOCountry("BG", Franchise.european),
    "Burkina Faso" -> ISOCountry("BF"),
    "Burma" -> ISOCountry("MM"),
    "Burundi" -> ISOCountry("bi"),
    "Cambodia" -> ISOCountry("KH"),
    "Cameroon" -> ISOCountry("CM", Franchise.commonwealth),
    "Canada" -> ISOCountry("CA", Franchise.commonwealth),
    "Cape Verde" -> ISOCountry("CV"),
    "Cayman Islands" -> ISOCountry("KY", Franchise.britishTerritories),
    "Central African Republic" -> ISOCountry("CF"),
    "Chad" -> ISOCountry("td"),
    "Chile" -> ISOCountry("CL"),
    "China" -> ISOCountry("CN"),
    "Colombia" -> ISOCountry("CO"),
    "Comoros" -> ISOCountry("KM"),
    "Congo" -> ISOCountry("CG"),
    "Costa Rica" -> ISOCountry("CR"),
    "Cote d’Ivoire" -> ISOCountry("CI"),
    "Croatia" -> ISOCountry("HR", Franchise.european),
    "Cuba" -> ISOCountry("CU"),
    "Curaçao" -> ISOCountry("CW"),
    "Cyprus" -> ISOCountry("CY", Franchise.european, Franchise.commonwealth),
    "Czech Republic" -> ISOCountry("CZ", Franchise.european),
    "Democratic Republic of Congo" -> ISOCountry("CD"),
    "Denmark" -> ISOCountry("DK", Franchise.european),
    "Djibouti" -> ISOCountry("DJ"),
    "Dominica" -> ISOCountry("DM", Franchise.commonwealth),
    "Dominican Republic" -> ISOCountry("DO"),
    "Ecuador" -> ISOCountry("EC"),
    "Egypt" -> ISOCountry("EG"),
    "El Salvador" -> ISOCountry("sv"),
    "Equatorial Guinea" -> ISOCountry("GQ"),
    "Eritrea" -> ISOCountry("ER"),
    "Estonia" -> ISOCountry("EE", Franchise.european),
    "Ethiopia" -> ISOCountry("ET"),
    "Falkland Islands" -> ISOCountry("fk", Franchise.britishTerritories),
    "Fiji" -> ISOCountry("FJ", Franchise.commonwealth),
    "Finland" -> ISOCountry("FI", Franchise.european),
    "France" -> ISOCountry("FR", Franchise.european),
    "French Guiana" -> ISOCountry("GF"),
    "French Polynesia" -> ISOCountry("PF"),
    "Gabon" -> ISOCountry("GA"),
    "Gambia" -> ISOCountry("GM", Franchise.commonwealth),
    "Georgia" -> ISOCountry("GE"),
    "Germany" -> ISOCountry("DE", Franchise.european),
    "Ghana" -> ISOCountry("GH", Franchise.commonwealth),
    "Gibraltar" -> ISOCountry("GI", Franchise.britishTerritories),
    "Greece" -> ISOCountry("GR", Franchise.european),
    "Grenada" -> ISOCountry("GD", Franchise.commonwealth),
    "Guadeloupe" -> ISOCountry("GP"),
    "Guatemala" -> ISOCountry("GT"),
    "Guinea" -> ISOCountry("gn"),
    "Guinea-Bissau" -> ISOCountry("GW"),
    "Guyana" -> ISOCountry("GY", Franchise.commonwealth),
    "Haiti" -> ISOCountry("HT"),
    "Holy See" -> ISOCountry("VA"),
    "Honduras" -> ISOCountry("HN"),
    "Hong Kong" -> ISOCountry("HK"),
    "Hungary" -> ISOCountry("HU", Franchise.european),
    "Iceland" -> ISOCountry("IS"),
    "India" -> ISOCountry("IN", Franchise.commonwealth),
    "Indonesia" -> ISOCountry("ID"),
    "Iran" -> ISOCountry("IR"),
    "Iraq" -> ISOCountry("IQ"),
    "Ireland" -> ISOCountry("IE", Franchise.full, Franchise.european),
    "Israel" -> ISOCountry("IL"),
    "Italy" -> ISOCountry("IT", Franchise.european),
    "Jamaica" -> ISOCountry("JM", Franchise.commonwealth),
    "Japan" -> ISOCountry("JP"),
    "Jordan" -> ISOCountry("JO"),
    "Kazakhstan" -> ISOCountry("KZ"),
    "Kenya" -> ISOCountry("KE", Franchise.commonwealth),
    "Kiribati" -> ISOCountry("KI", Franchise.commonwealth),
    "Kuwait" -> ISOCountry("KW"),
    "Kyrgyzstan" -> ISOCountry("kg"),
    "Laos" -> ISOCountry("LA"),
    "Latvia" -> ISOCountry("LV", Franchise.european),
    "Lebanon" -> ISOCountry("LB"),
    "Lesotho" -> ISOCountry("LS", Franchise.commonwealth),
    "Liberia" -> ISOCountry("LR"),
    "Libya" -> ISOCountry("LY"),
    "Liechtenstein" -> ISOCountry("LI"),
    "Lithuania" -> ISOCountry("LT", Franchise.european),
    "Luxembourg" -> ISOCountry("LU", Franchise.european),
    "Macao" -> ISOCountry("MO"),
    "Macedonia" -> ISOCountry("MK"),
    "Madagascar" -> ISOCountry("MG"),
    "Malawi" -> ISOCountry("MW", Franchise.commonwealth),
    "Malaysia" -> ISOCountry("MY", Franchise.commonwealth),
    "Maldives" -> ISOCountry("MV", Franchise.commonwealth),
    "Mali" -> ISOCountry("ML"),
    "Malta" -> ISOCountry("MT", Franchise.european, Franchise.commonwealth),
    "Marshall Islands" -> ISOCountry("MH"),
    "Martinique" -> ISOCountry("MQ"),
    "Mauritania" -> ISOCountry("mr"),
    "Mauritius" -> ISOCountry("MU", Franchise.commonwealth),
    "Mayotte" -> ISOCountry("YT"),
    "Mexico" -> ISOCountry("MX"),
    "Micronesia" -> ISOCountry("FM"),
    "Moldova" -> ISOCountry("MD"),
    "Monaco" -> ISOCountry("MC"),
    "Mongolia" -> ISOCountry("MN"),
    "Montenegro" -> ISOCountry("ME"),
    "Montserrat" -> ISOCountry("MS", Franchise.britishTerritories),
    "Morocco" -> ISOCountry("MA"),
    "Mozambique" -> ISOCountry("MZ", Franchise.commonwealth),
    "Namibia" -> ISOCountry("NA", Franchise.commonwealth),
    "Nauru" -> ISOCountry("NR", Franchise.commonwealth),
    "Nepal" -> ISOCountry("NP"),
    "Netherlands" -> ISOCountry("NL", Franchise.european),
    "New Caledonia" -> ISOCountry("NC"),
    "New Zealand" -> ISOCountry("NZ", Franchise.commonwealth),
    "Nicaragua" -> ISOCountry("NI"),
    "Niger" -> ISOCountry("NE"),
    "Nigeria" -> ISOCountry("NG", Franchise.commonwealth),
    "North Korea" -> ISOCountry("KP"),
    "Norway" -> ISOCountry("NO"),
    "Oman" -> ISOCountry("OM"),
    "Pakistan" -> ISOCountry("PK", Franchise.commonwealth),
    "Palau" -> ISOCountry("PW"),
    "Panama" -> ISOCountry("PA"),
    "Papua New Guinea" -> ISOCountry("PG", Franchise.commonwealth),
    "Paraguay" -> ISOCountry("PY"),
    "Peru" -> ISOCountry("PE"),
    "Philippines" -> ISOCountry("PH"),
    "Pitcairn Island" -> ISOCountry("pn", Franchise.britishTerritories),
    "Poland" -> ISOCountry("PL", Franchise.european),
    "Portugal" -> ISOCountry("PT", Franchise.european),
    "Qatar" -> ISOCountry("QA"),
    "Réunion" -> ISOCountry("RE"),
    "Romania" -> ISOCountry("RO", Franchise.european),
    "Russia" -> ISOCountry("RU"),
    "Rwanda" -> ISOCountry("RW", Franchise.commonwealth),
    "Samoa" -> ISOCountry("WS", Franchise.commonwealth),
    "San Marino" -> ISOCountry("SM"),
    "São Tomé and Principe" -> ISOCountry("ST"),
    "Saudi Arabia" -> ISOCountry("SA"),
    "Senegal" -> ISOCountry("SN"),
    "Serbia" -> ISOCountry("RS"),
    "Seychelles" -> ISOCountry("SC", Franchise.commonwealth),
    "Sierra Leone" -> ISOCountry("SL", Franchise.commonwealth),
    "Singapore" -> ISOCountry("SG", Franchise.commonwealth),
    "Slovakia" -> ISOCountry("SK", Franchise.european),
    "Slovenia" -> ISOCountry("SI", Franchise.european),
    "Solomon Islands" -> ISOCountry("SB", Franchise.commonwealth),
    "Somalia" -> ISOCountry("SO"),
    "South Africa" -> ISOCountry("ZA", Franchise.commonwealth),
    "South Georgia and the South Sandwich Islands" -> ISOCountry("GS", Franchise.britishTerritories),
    "South Korea" -> ISOCountry("KR"),
    "South Sudan" -> ISOCountry("SS"),
    "Spain" -> ISOCountry("ES", Franchise.european),
    "Sri Lanka" -> ISOCountry("LK", Franchise.commonwealth),
    "St Helena, Ascension and Tristan Da Cunha" -> ISOCountry("sh", Franchise.britishTerritories),
    "St Kitts and Nevis" -> ISOCountry("KN", Franchise.commonwealth),
    "St Lucia" -> ISOCountry("lc", Franchise.commonwealth),
    "St Maarten" -> ISOCountry("MF"),
    "St Pierre & Miquelon" -> ISOCountry("PM"),
    "St Vincent and the Grenadines" -> ISOCountry("VC", Franchise.commonwealth),
    "Sudan" -> ISOCountry("SD"),
    "Suriname" -> ISOCountry("SR"),
    "Swaziland" -> ISOCountry("SZ", Franchise.commonwealth),
    "Sweden" -> ISOCountry("SE", Franchise.european),
    "Switzerland" -> ISOCountry("CH"),
    "Syria" -> ISOCountry("SY"),
    "Taiwan" -> ISOCountry("TW"),
    "Tajikistan" -> ISOCountry("TJ"),
    "Tanzania" -> ISOCountry("TZ", Franchise.commonwealth),
    "Thailand" -> ISOCountry("TH"),
    "The Occupied Palestinian Territories" -> ISOCountry("PS"),
    "Timor Leste" -> ISOCountry("TL"),
    "Togo" -> ISOCountry("TG"),
    "Tonga" -> ISOCountry("TO", Franchise.commonwealth),
    "Trinidad and Tobago" -> ISOCountry("TT", Franchise.commonwealth),
    "Tunisia" -> ISOCountry("TN"),
    "Turkey" -> ISOCountry("TR"),
    "Turkmenistan" -> ISOCountry("TM"),
    "Turks and Caicos Islands" -> ISOCountry("TC", Franchise.britishTerritories),
    "Tuvalu" -> ISOCountry("TV", Franchise.commonwealth),
    "Uganda" -> ISOCountry("UG", Franchise.commonwealth),
    "Ukraine" -> ISOCountry("UA"),
    "United Arab Emirates" -> ISOCountry("AE"),
    "United Kingdom" -> ISOCountry("GB", Franchise.full, Franchise.european, Franchise.commonwealth),
    "Uruguay" -> ISOCountry("UY"),
    "Usa" -> ISOCountry("US"),
    "Uzbekistan" -> ISOCountry("UZ"),
    "Vanuatu" -> ISOCountry("VU", Franchise.commonwealth),
    "Venezuela" -> ISOCountry("VE"),
    "Vietnam" -> ISOCountry("VN"),
    "Wallis and Futuna" -> ISOCountry("WF"),
    "Western Sahara" -> ISOCountry("EH"),
    "Yemen" -> ISOCountry("YE"),
    "Zambia" -> ISOCountry("ZM", Franchise.commonwealth),
    "Zimbabwe" -> ISOCountry("ZW", Franchise.commonwealth)
  )
}
