#!/bin/bash

set -e

thisDir="$( dirname "$0" )"
cd `pwd`

playVersion=$(<$thisDir/playVersion)

updateTemplate=$thisDir/../update-template.sh

installPlay="$thisDir/setup-play.sh"
play="$thisDir/../bin/play-$playVersion/play"

if [ ! -f "$play" ]; then 
  echo "Play not found. Installing play"
  echo `$installPlay` 
fi

if [ -z "$JENKINS_HOME" ]; then
	SBT_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9999"
fi

$updateTemplate
$play debug $@
